[architecture]
    name = "conv_classifier_test"
    input_size = [10, 10, 3]

layers = [
    {f = "conv", out=10, filter=[5,5], sigma="relu"},
    {f = "conv", out=3, filter=[5,5], sigma="relu"},
    {f = "dense", out=10, sigma="relu"}
]