layers = [
    {f = "conv", out=10, filter=[5,5], sigma="relu"},
    {f = "conv", out=3, filter=[5,5], sigma="relu"},
    {f = "rpm", out=[2,2,2], sigma="relu", pad=3, timeblock=3},
    {f = "dense", out=10, sigma="relu"}
]