[training]

[training.data]
num_epochs = 100
batch_size = 32
input_size = [28, 28, 1]

[training.task]
supervised = false

[training.optimizer]
name = "ADAM"
params = { lr = 0.01 }

[training.loss]
name = "vae_loss"
beta=1.0

[model]
type = "vae"
paths = {encoder = "./static/conv.toml", decoder = "./static/conv_d.toml", latent="./static/latent.toml"}